name: CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and validate Bicep files
        run: bicep build main.bicep

  deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Bicep template
        env:
          MYSECRET: ${{ secrets.MYSECRET }}
        run: |
          bicep build main.bicep
          az deployment group create --resource-group <resource-group-name> --template-file main.json --parameters parameters.json