name: CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Bicep
        uses: azure/setup-bicep@v1

      - name: Build and validate Bicep files
        run: docker run --rm -v ${{ github.workspace }}:/workspace mcr.microsoft.com/azure-cli/bicep:latest build /workspace/main.bicep

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Bicep
        uses: azure/setup-bicep@v1

      - name: Deploy Bicep template
        env:
          MYSECRET: ${{ secrets.MYSECRET }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace mcr.microsoft.com/azure-cli/bicep:latest build /workspace/main.bicep